// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpxYvMVr5Oplj5DL70wMZ9LyCBtpSJmTw',
    appId: '1:165595934478:web:4d254f72be1c174bdc315f',
    messagingSenderId: '165595934478',
    projectId: 'testchat-b78fd',
    authDomain: 'testchat-b78fd.firebaseapp.com',
    storageBucket: 'testchat-b78fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdP0SFaWhwAWdhT2giql3y3G8pmmNUS8',
    appId: '1:165595934478:android:04cca87a455707cbdc315f',
    messagingSenderId: '165595934478',
    projectId: 'testchat-b78fd',
    storageBucket: 'testchat-b78fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfZNVNeObjG5JBXajAIPlSDbeTcrHAOGo',
    appId: '1:165595934478:ios:d23e68aef25016eadc315f',
    messagingSenderId: '165595934478',
    projectId: 'testchat-b78fd',
    storageBucket: 'testchat-b78fd.appspot.com',
    iosBundleId: 'com.example.testchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfZNVNeObjG5JBXajAIPlSDbeTcrHAOGo',
    appId: '1:165595934478:ios:5ee75a6af259c483dc315f',
    messagingSenderId: '165595934478',
    projectId: 'testchat-b78fd',
    storageBucket: 'testchat-b78fd.appspot.com',
    iosBundleId: 'com.example.testchat.RunnerTests',
  );
}
